// Copy for the /dev/components preview. Sample people and numbers are
// fictional (ACMA 0491 570 xxx mobiles, example.com emails).

export const devComponentsContent = {
  metadataTitle: "Components — Millstone",
  title: "Components",
  intro:
    "Every shared component in each variant and state, first in the customer context and then inside data-context=\"admin\".",
  valueLabel: "Value",
  frames: {
    customer: "Customer (default)",
    admin: 'Admin (data-context="admin")',
  },
  sections: {
    button: "Button",
    labels: "StatusBadge, PaymentLabel, RecurringLabel, RecurringStatusTag",
    textField: "TextField",
    quantityStepper: "QuantityStepper",
    toggle: "Toggle",
    choiceGroup: "ChoiceGroup",
    notice: "Notice",
    weekdayPicker: "WeekdayPicker",
    datePicker: "DatePicker",
    productCard: "ProductCard and Card",
    orderRow: "OrderRow (admin only)",
    sheet: "Sheet",
    dialog: "Dialog",
  },
  captions: {
    variants: "Variants",
    withIcon: "With an icon",
    disabled: "Disabled",
    block: "Block (full width)",
    counter: "Counter (72px on the admin)",
    orderStatus: "Order status",
    payment: "Payment",
    paymentCustomer: "Payment, customer wording",
    recurring: "Recurring",
    controlled: "Controlled",
    uncontrolled: "Uncontrolled",
    atMin: "At the minimum",
    atOne: "At 1 (minus removes)",
    atMax: "At the maximum",
    withError: "With an error",
    nothingChosen: "Controlled, nothing chosen yet",
    recurringDays: "Recurring, showing the days",
    recurringStatus: "Recurring order status",
    info: "Info tone: plain flour, never delft",
    focusTarget: "Dismiss sends focus to a control the screen chooses",
    closedDays: "With closed days",
    strip: "Strip (customers)",
    stripUnavailable: "Strip: 14 days, one sold-out day, Mondays closed",
    month: "Month (admin filter, recurring dates)",
    card: "Card",
    productGrid: "Two-column grid: add, in the order, sold out for a day, sold out, with a photo",
    rowLayout: "Row layout",
    everyStatus: "Every status and payment combination",
    sheet: "Bottom sheet",
    customerDialog: "Warning that needs an answer (alertdialog)",
    confirmPayment: "Confirm payment",
    cancelOrder: "Cancel with a reason",
    lastAction: "Last action",
  },
  button: {
    primary: "Place order",
    secondary: "Add more items",
    quiet: "Menu",
    danger: "Cancel order",
    ready: "Collected",
    disabled: "Choose a date first",
    block: "Go to checkout",
    counterReady: "Ready",
    counterCollected: "Collected",
  },
  labels: {
    payAtPickup: "Pay at pickup",
  },
  textField: {
    name: { label: "Name", error: "Enter your name." },
    phone: {
      label: "Mobile number",
      hint: "So we can call if something changes.",
      error: "Enter a 10-digit mobile number, like 0491 570 156.",
      value: "0491 570",
    },
    email: { label: "Email", hint: "We'll send your confirmation here." },
    notes: { label: "Notes for the bakery", hint: "Like “Sliced, please”." },
    disabled: { label: "Branch", value: "Northcote" },
    search: { label: "Find an order", placeholder: "Order number, name or phone" },
  },
  quantityStepper: {
    product: "Plain bagel",
    maxProduct: "Sourdough rye loaf",
  },
  toggle: {
    product: "Sourdough rye loaf",
    onText: "On the menu",
    offText: "Off the menu",
    disabledProduct: "Fruit loaf",
  },
  choiceGroup: {
    payment: {
      label: "How would you like to pay?",
      options: [
        {
          value: "online",
          label: "Pay online now",
          hint: "Pay by card on a secure payment page, then come back here.",
        },
        {
          value: "at_pickup",
          label: "Pay at pickup",
          hint: "Pay at the counter when you collect your order.",
        },
      ],
      error: "Choose how you'd like to pay.",
    },
    reason: {
      label: "Why is it being cancelled?",
      options: [
        { value: "not_collected", label: "Not collected", hint: "The customer didn’t come in for it." },
        { value: "customer", label: "Customer request", hint: "They called or came in to cancel." },
        { value: "other", label: "Other", hint: "Anything else. You’ll be asked what happened." },
      ],
    },
    none: "none",
  },
  notice: {
    neutral:
      "We took Sourdough rye loaf out of your order because Fitzroy doesn't make it.",
    neutralCheckTitle: "Your account is set up",
    neutralCheckBody: "You're signed in as sam.carter@example.com, and this order is in My account.",
    errorTitle: "Your payment wasn't completed",
    errorBody:
      "You haven't been charged, and your order and details are just as you left them. Try again, or choose Pay at pickup.",
    success: "MS-1043 collected",
    undo: "Undo",
    undoLabel: "Undo: put MS-1043 back to Ready",
    warningTitle: "Hiding takes it off all three menus.",
    warningBody:
      "Orders already placed keep it at the price they paid. Recurring orders will leave it out and say why in their note.",
    info: "New products go on the menu at all three branches. A branch that doesn’t make it can switch it off in Availability.",
    dismissed: "Dismissed. Reload to see it again.",
    targetButton: "Change branch",
  },
  weekdayPicker: {
    label: "Pickup days",
    hint: "Choose one or more. We make each order at 2pm the day before.",
    error: "Choose at least one day.",
  },
  datePicker: {
    stripLabel: "Pickup day",
    stripNote: "Order by 2pm for next-day pickup. Closed Mondays.",
    monthLabel: "Show orders for",
    monthNote: "Closed Mondays.",
    none: "none",
  },
  productCard: {
    cardTitle: "Pickup from",
    cardBody: "Northcote",
    products: {
      rye: { name: "Sourdough rye loaf", priceCents: 950, description: "800g, dark crust, caraway." },
      seeded: { name: "Seeded sandwich loaf", priceCents: 850, description: "Sliced, for the week." },
      croissant: { name: "Almond croissant", priceCents: 600, description: "Twice-baked, frangipane." },
      scroll: { name: "Cinnamon scroll", priceCents: 500, description: "Brown sugar, cardamom." },
      bagel: { name: "Plain bagel", priceCents: 280, description: "Boiled, then baked." },
    },
    soldOutFor: (day: string) => `Sold out for ${day}`,
    // The sample image is a generated colour swatch, not a product photo.
    imageAlt: "",
  },
  orderRow: {
    generationNote: "Rye loaf \u00d74 skipped: sold out",
    notes: "Sliced, please",
    cafeNotes: "Back door on Elm Lane, before 7am",
    ready: (orderNumber: string) => `${orderNumber}: Ready pressed`,
    collected: (orderNumber: string) => `${orderNumber}: Collected pressed`,
    opened: (orderNumber: string) => `${orderNumber}: Details pressed`,
    none: "none",
  },
  sheet: {
    open: "Change branch",
    title: "Pick up from",
    question: "Which branch?",
    branches: ["Northcote", "Fitzroy", "Brunswick"],
    note: "Prices are the same at every branch. Some items are only made at one branch.",
    confirm: (branch: string) => `Pick up from ${branch}`,
    keep: (branch: string) => `Keep ${branch}`,
    cancel: "Cancel",
    result: "Branch",
  },
  dialog: {
    warning: {
      open: "Change to Fitzroy",
      title: "Change to Fitzroy?",
      description: "Fitzroy doesn't make this, so we'll take it out of your order:",
      removed: "1 \u00d7 Sourdough rye loaf",
      confirm: "Change to Fitzroy",
      keep: "Keep Northcote",
    },
    confirmPayment: {
      open: "Collect an unpaid order",
      orderNumber: "MS-1042",
      title: (name: string) => `Has ${name} paid?`,
      customerName: "Priya Nair",
      totalCents: 1630,
      bodyBefore: "They chose to pay at pickup. Take ",
      bodyAfter: " before you hand the order over.",
      confirm: "Yes, paid \u00b7 Collected",
      notYet: "Not yet",
    },
    cancel: {
      open: "Cancel an order",
      title: "Cancel MS-1044?",
      totalCents: 8600,
      description: (total: string, day: string) =>
        `Corner Cup Cafe \u00b7 ${total} \u00b7 pickup ${day}. A cancelled order can't be reopened.`,
      otherLabel: "What happened?",
      otherHint: "A few words for whoever looks at this order next.",
      refundTitle: "Paid online: remember the refund",
      refundBody: (total: string) =>
        `Cancelling doesn't send the ${total} back. Refund it in the payment provider's dashboard, then tap Mark refunded on this order.`,
      confirm: "Cancel order",
      chooseFirst: "Choose a reason first",
      keep: "Keep order",
    },
    results: { confirmed: "confirmed", closed: "closed" },
  },
} as const;
